### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by marksantoso** [josh-wer/form-validate.js#10]
Failed to compile

./node_modules/form-validate.js/lib/form-validate.js
Module not found: Can't resolve ' web-app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js' in ' web-app'

**Comment by josh-wer** [comment]
The error seems to be coming from a package outside form-validate.js
`web-app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js`
I suggest removing the `node_modules` folder and running npm install.
However, if you do not mind, you can paste the code snippet so it can be reviewed.

**Comment by marksantoso** [comment]
`import FormValidate from "form-validate.js"`

**Comment by josh-wer** [comment]
I see that. Is this all you have at the moment? have you tried creating an instance of the validator?

**Comment by marksantoso** [comment]
>  I suggest removing the node_modules folder and running npm install.

that was it 👍

**Comment by josh-wer** [comment]
Great! kindly do leave a review and star the project.
I believe this issue can be closed now?
